### ISSUE TITLE
Error Saving Data

### ISSUE THREAD

**Issue by davin12x** [KevinCoble/swift-libsvm#2]
Hi I am Having Issues in Saving data

Error Code  is Error Domain=Beacons.SVMModel.SVMWriteErrors Code=0 "(null)"

**Comment by KevinCoble** [comment]
The only error thrown from the write is from the following line:

```
        if !pList.writeToFile(path, atomically: false) { throw SVMWriteErrors.failedWriting }
```

pList is an NSDictionary containing the model information.  The error could occur if pList contained non property-list items, but I would expect that would have been found before.  The most likely error is with the path, or permissions writing to the path.  Check the path being sent to the 'saveToFile(path: String)' method, making sure it is a valid file name, and the user has permission to write to that path.

By the way, the SVM library has been subsumed by the AIToolbox framework.  Any future work on the Swift SVM code will be done under that project.

**Comment by davin12x** [comment]
Yes .. What i found is writeToFile gives false value . But when i try to save normally text . It is working . Anyways thanks
